import { Forecast } from '~/types'

export const forecast: Forecast = {
  location: {
    name: 'Tokyo',
    region: 'TÅkyÅ',
    country: 'Japan',
    lat: 35.69,
    lon: 139.69,
    tz_id: 'Asia/Tokyo',
    localtime_epoch: 1594977674,
    localtime: '2020-07-17 18:21',
  },
  current: {
    last_updated_epoch: 1594977322,
    last_updated: '2020-07-17 18:15',
    temp_c: 20,
    temp_f: 68,
    is_day: 1,
    condition: {
      text: 'Light rain shower',
      icon: '//cdn.weatherapi.com/weather/64x64/day/353.png',
      code: 1240,
    },
    wind_mph: 11.9,
    wind_kph: 19.1,
    wind_degree: 40,
    wind_dir: 'NE',
    pressure_mb: 1011,
    pressure_in: 30.3,
    precip_mm: 0.6,
    precip_in: 0.02,
    humidity: 94,
    cloud: 75,
    feelslike_c: 20,
    feelslike_f: 68,
    vis_km: 10,
    vis_miles: 6,
    uv: 6,
    gust_mph: 12.1,
    gust_kph: 19.4,
  },
  forecast: {
    forecastday: [
      {
        date: '2020-07-17',
        date_epoch: 1594944000,
        day: {
          maxtemp_c: 26.5,
          maxtemp_f: 79.7,
          mintemp_c: 21.5,
          mintemp_f: 70.7,
          avgtemp_c: 23.6,
          avgtemp_f: 74.5,
          maxwind_mph: 9.4,
          maxwind_kph: 15.1,
          totalprecip_mm: 4.1,
          totalprecip_in: 0.16,
          avgvis_km: 6.9,
          avgvis_miles: 4,
          avghumidity: 73,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 95,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Light drizzle',
            icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
            code: 1153,
          },
          uv: 7,
        },
        astro: {
          sunrise: '04:38 AM',
          sunset: '06:56 PM',
          moonrise: '01:21 AM',
          moonset: '03:50 PM',
        },
      },
      {
        date: '2020-07-18',
        date_epoch: 1595030400,
        day: {
          maxtemp_c: 24.3,
          maxtemp_f: 75.7,
          mintemp_c: 16.3,
          mintemp_f: 61.3,
          avgtemp_c: 22.1,
          avgtemp_f: 71.8,
          maxwind_mph: 10.1,
          maxwind_kph: 16.2,
          totalprecip_mm: 41.4,
          totalprecip_in: 1.63,
          avgvis_km: 8,
          avgvis_miles: 4,
          avghumidity: 83,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 5,
        },
        astro: {
          sunrise: '04:39 AM',
          sunset: '06:56 PM',
          moonrise: '02:01 AM',
          moonset: '04:50 PM',
        },
      },
      {
        date: '2020-07-19',
        date_epoch: 1595116800,
        day: {
          maxtemp_c: 27.7,
          maxtemp_f: 81.9,
          mintemp_c: 24.2,
          mintemp_f: 75.6,
          avgtemp_c: 25.7,
          avgtemp_f: 78.3,
          maxwind_mph: 17.2,
          maxwind_kph: 27.7,
          totalprecip_mm: 0.5,
          totalprecip_in: 0.02,
          avgvis_km: 9.4,
          avgvis_miles: 5,
          avghumidity: 71,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 78,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain at times',
            icon: '//cdn.weatherapi.com/weather/64x64/day/299.png',
            code: 1186,
          },
          uv: 5,
        },
        astro: {
          sunrise: '04:39 AM',
          sunset: '06:55 PM',
          moonrise: '02:48 AM',
          moonset: '05:49 PM',
        },
      },
    ],
  },
  alert: {},
}
