version: '3.1'

services:
  nextjs-template:
    container_name: nextjs-template
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./out:/usr/share/nginx/html:cached
    restart: always
